config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :albums, only: %i[index new create edit update destroy] do
    resources :tracks, only: %i[index new edit update destroy]
  end

  post 'publications/albums/:album_id', to: 'publications#create', as: 'publications'

  root to: 'albums#index'

  if Rails.env.development? || Rails.env.test?
    post 'session_without_csrf', to: 'sessions#create_without_csrf'
    delete 'session_without_csrf', to: 'sessions#destroy_without_csrf'
  end
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_one_attached :cover_image

  has_many :tracks, dependent: :destroy
  belongs_to :created_by, class_name: :User, optional: true

  accepts_nested_attributes_for :tracks, allow_destroy: true
  validates :name, presence: true

  scope :published, -> { where.not(published_at: nil) }

  def publish!
    update!(published_at: Time.zone.now)
  end

  def published?
    published_at.present?
  end

  def total_album_duration
    tracks.sum(:duration)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/track.rb
# frozen_string_literal: true

class Track < ApplicationRecord
  belongs_to :album
  validates :title, :duration, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  before_action :require_login, except: :index
  before_action :set_album, only: %i[show edit update destroy]
  before_action :ensure_frame_response, only: %i[new edit]

  def index
    authorize :album, :index?
    scope = policy_scope(Album).includes(:tracks)
    @albums = scope.paginate(page: params[:page], per_page: 10)
                   .order(published_at: :asc, id: :desc)
  end

  def show; end

  # GET /albums/new
  def new
    @album = Album.new
  end

  def edit; end

  # rubocop:disable Metrics/AbcSize
  def create
    @album = Album.new(album_params)
    @album.created_by = current_user

    respond_to do |format|
      if @album.save
        flash.now[:notice] = "#{@album.name} was successfully created."
        # to refresh whole list
        # format.turbo_stream { render turbo_stream: turbo_stream.action(:refresh, '') }

        # To make flash message work in turbo, I have followed these solutions (I know it's not kind of good practice)
        # TODO: move flash messages in JS
        # https://discuss.hotwired.dev/t/flash-messages-with-turbo/2345/14
        # https://hivekind.com/blog/exploring-flash-messages-with-turbo-streams-in-rails-7

        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend(
              'albums',
              partial: 'albums/album',
              locals: { album: @album }
            ),
            turbo_stream.replace('flash', partial: 'application/flash')
          ]
        end
        format.html { redirect_to album_url(@album), notice: 'Album was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  # rubocop:disable Metrics/AbcSize
  def update
    respond_to do |format|
      if @album.update(album_params)
        flash.now[:notice] = "#{@album.name} was successfully updated."

        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(
              @album,
              partial: 'albums/album',
              locals: { album: @album }
            ),
            turbo_stream.replace('flash', partial: 'application/flash')
          ]
        end
        format.html { redirect_to album_url(@album), notice: 'Album was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = policy_scope(Album).find(params[:id])
    authorize @album, "#{action_name}?".to_sym
  end

  def ensure_frame_response
    return unless Rails.env.development?
    redirect_to root_path unless turbo_frame_request?
  end

  def album_params
    params
      .require(:album)
      .permit(
        :name,
        :cover_image,
        tracks_attributes: %i[id title artist duration _destroy]
      )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit::Authorization
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

class PublicationsController < ApplicationController
  before_action :require_login

  def create
    @album = Album.find(params[:album_id])
    authorize @album, :publish?

    @album.publish!
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album published successfully.' }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Clearance::SessionsController
  skip_before_action :verify_authenticity_token, only: %i[create_without_csrf destroy_without_csrf]

  # To authenticate in Cypress test
  def create_without_csrf
    @user = authenticate(params)
    sign_in(@user)
  end

  def destroy_without_csrf
    sign_out
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def duration_string(time_sec)
    formatter = time_sec >= 3600 ? '%H:%M:%S' : '%M:%S'
    Time.at(time_sec).utc.strftime(formatter)
  end
end

app/views/albums/_album.html.erb
<div class="bg-white rounded-lg shadow-md p-4 border-2 border-gray-200 mb-4" id="<%= dom_id album %>" data-cy="album-<%= album.id %>">
  <div class="flex justify-between">
    <div class="flex">
      <div class="border min-w-48 max-w-48 min-h-48 max-h-48 mr-4 flex justify-center items-center"><%= album.cover_image.attached? ? image_tag(album.cover_image) : 'No Cover' %></div>
      <div class="flex flex-col justify-center">
        <h2 class="text-2xl font-semibold" data-cy="alb-title-<%= album.id %>"><%= album.name %></h2>
        <div class=""><%= duration_string(album.total_album_duration) %></div>
      </div>
    </div>
    <div class="flex items-start justify-end">
      <div class="flex">
        <% if album.published? %>
          <i data-cy="publish-text-<%= album.id %>">Published on <%= l album.published_at %></i>
        <% else %>
          <%= link_to "Publish", publications_path(album), class: "font-medium mr-2" , data: {
            turbo_method: :post,
            turbo_confirm: "Are you sure?",
            cy: "publish-#{album.id}"
          } if AlbumPolicy.new(current_user, album).publish? %> |
          <%= button_to 'Edit',
                        edit_album_path(album),
                        method: :get,
                        class: "font-medium ml-2 mr-2",
                        data: {
                          turbo_frame: 'modal',
                          cy: "edit-#{album.id}"
                        } if AlbumPolicy.new(current_user, album).edit? %> |
          <%= link_to "Delete", album, class: "font-medium ml-2", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?",
            cy: "delete-#{album.id}"
          } if AlbumPolicy.new(current_user, album).destroy? %>
        <% end %>
      </div>
    </div>
  </div>
  <hr class="h-0.5 bg-gray-200 mx-auto my-4 bg-opacity-30">

  <% album.tracks.each_with_index do |track, index| %>
    <div class="track flex mx-4 justify-between <%= 'border-b-2' if index + 1 != album.tracks.count %>">
      <div>
        <div><h2 class="text-l font-semibold" data-cy="track-<%= track.id %>-title"><%= track.title %></h2></div>
        <div class="text-slate-500"><%= track.artist %></div>
      </div>
      <div class="flex justify-center items-center"><%= duration_string track.duration %></div>
    </div>
  <% end %>

  <% if album.tracks.blank? %>
    <i>No track found</i>
  <% end %>
</div>

app/views/albums/_form.html.erb
<%= form_with(model: album, class: "contents", data: { controller: 'album' }) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg my-3">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-4 gap-2">
    <div class="col-span-1">
      <div class="max-w-xl flex flex-col items-center justify-center">
        <label
          for="album_cover_image"
          class="flex justify-center w-full h-32 transition bg-white border-2 border-gray-300 border-dashed rounded-md appearance-none cursor-pointer hover:border-gray-400 focus:outline-none relative mb-2">
          <%= form.file_field :cover_image, class: "hidden", data: { album_target: 'uploadCoverInput' } %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="absolute inset-y-1/2" viewBox="0 0 16 16">
            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
            <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708z"/>
          </svg>
          <img data-album-target="coverPreview" src="<%= form.object.cover_image.attached? ? url_for(form.object.cover_image) : "#" %>" alt="cover image" class="<%= 'hidden' unless form.object.cover_image.attached? %>">
        </label>

        <div class="flex items-center space-x-2">
          <span class="text-sm text-gray-600" data-album-target="uploadText" data-cy="upload-cover-text"><%= form.object.cover_image.attached? ? 'Change' : 'Add' %> cover</span>
        </div>
      </div>
    </div>
    <div class="col-span-3 flex items-center">
      <%= form.text_field :name, placeholder: 'Album name', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-full", data: { cy: 'album-name-input' } %>
    </div>
  </div>

  <hr class="h-0.5 bg-gray-200 mx-auto my-4 bg-opacity-30">

  <div class="px-4" data-controller="track">
    <div class="tracks-list overflow-y-scroll max-h-80" data-track-target="trackList">
      <%= form.fields_for :tracks do |track_form| %>
        <div class="track-item grid grid-cols-1 md:grid-cols-10 gap-1 pb-2 border-b-2 mb-2" data-track-target="trackItem" data-cy="track-item">
          <%= track_form.text_field :title, placeholder: 'Track Title', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 col-span-4" %>
          <%= track_form.text_field :artist, placeholder: 'Artist Name', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 col-span-3" %>
          <%= track_form.number_field :duration, placeholder: 'Duration (sec)', class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 col-span-2" %>
          <%= track_form.check_box :_destroy, class: "hidden destroy-checkbox" %>
          <a class="remove-track col-span-1 flex justify-center items-center" data-track-target="removeTrackButton" href="javascript:void(0)" data-cy="remove-track">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
              <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
            </svg>
          </a>
        </div>
      <% end %>
    </div>
    <%= link_to '+ Add Track', 'javascript:void(0)', class: "font-semibold", data: { track_target: "addTrackButton", cy: "add-track-button" } %>
  </div>

  <div class="flex justify-end">
    <%= form.submit "Save", class: "bg-blue-500 text-white px-4 py-2 rounded-sm hover:bg-blue-600 cursor-pointer", data: { cy: "submit-album" } %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<%= render ModalComponent.new(name: "Edit Album:") do %>
  <%= render "form", album: @album %>
<% end %>

app/views/albums/index.html.erb
<div class="flex justify-between items-center mb-4">
  <h1 class="text-3xl font-bold">Albums</h1>
  <%= button_to 'New album',
                new_album_path,
                method: :get,
                data: {
                  turbo_frame: 'modal',
                  cy: 'new-album'
                },
                class: "bg-blue-500 text-white px-4 py-2 rounded-sm hover:bg-blue-600"  if AlbumPolicy.new(current_user, nil).new? %>
</div>

<div id="albums" class="grid grid-cols-1">
  <% @albums.each do |album| %>
    <%= render album %>
  <% end %>

  <%= render partial: "shared/empty_state", locals: { type: "album" } if @albums.blank? %>
</div>
<%= will_paginate @albums %>

app/views/albums/new.html.erb
<%= render ModalComponent.new(name: "New Album") do %>
  <%= render "form", album: @album %>
<% end %>

app/views/application/_flash.html.erb
<div id="flash" class="w-1/2">
  <% flash.each do |key, value| %>
    <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400 flash <%= key %>" role="alert">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album Catalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag "modal" %>
    <main class="container max-w-screen-lg mx-auto mt-28 px-5">
      <div class="flex w-full justify-between mb-5">
        <h1 class="flex items-center text-5xl font-extrabold"><%= link_to 'Album Catalog', root_path, class: 'text-slate-500 hover:text-slate-400' %></h1>
        <div class="items-center flex">
          <% if signed_in? %>
            Signed in as: <span class="ml-2 text-blue-500 mr-2"><%= current_user.email %></span> |
            <%= button_to 'Sign out', sign_out_path, method: :delete, class: "ml-2 font-medium" %>
          <% else %>
            <%= link_to 'Sign in', sign_in_path, class: "font-medium mr-2" %> |
            <%= link_to 'Sign Up', sign_up_path, class: "font-medium ml-2 " %>
          <% end %>
        </div>
      </div>
      <%= render 'application/flash' %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_empty_state.html.erb
<div class="bg-white rounded-lg shadow-md p-4 border-2 border-gray-200 h-48 flex justify-center items-center">
  <i>No <%= local_assigns[:type] %> found!</i>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h3 class="text-3xl font-bold mb-2"><%= t(".title") %></h3>

  <div class="container flex">
    <%= form_for @user, data: { turbo: false } do |f| %>
      <div class="flex flex-col space-y-4">
        <div class="flex flex-col">
          <%= f.label :email, "Email", class: "text-gray-700 font-bold" %>
          <%= f.email_field :email, class: "border border-gray-300 rounded-md px-4 py-2" %>
        </div>
        <div class="flex flex-col">
          <%= f.label :password, "Password", class: "text-gray-700 font-bold" %>
          <%= f.password_field :password, class: "border border-gray-300 rounded-md px-4 py-2" %>
        </div>

        <div class="flex">
          <%= f.submit "Register", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
          <%= link_to t(".sign_in"), sign_in_path, class: "py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
        </div>
      </div>
    <% end %>
  </div>
</div>